package agents

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"strings"

	crewErrors "github.com/Ecook14/crewai-go/pkg/errors"
	"github.com/Ecook14/crewai-go/pkg/guardrails"
	"github.com/Ecook14/crewai-go/pkg/llm"
	"github.com/Ecook14/crewai-go/pkg/memory"
	"github.com/Ecook14/crewai-go/pkg/telemetry"
	"github.com/Ecook14/crewai-go/pkg/tools"
	"go.opentelemetry.io/otel/attribute"
)

var defaultLogger = slog.New(slog.NewTextHandler(os.Stdout, nil))

// Tool is a convenience alias for tools.Tool
type Tool = tools.Tool

// Agent translates the `class Agent` python abstraction into idiomatic Go.
type Agent struct {
	Role      string
	Goal      string
	Backstory string
	Verbose   bool

	LLM   llm.Client
	Tools []tools.Tool

	// Execution context limits
	MaxIterations        int
	MaxRetryLimit        int
	MaxRPM               int
	RespectContextWindow bool

	// Memory enables agents to recall and store context across executions.
	Memory memory.Store

	// EntityMemory stores specific named facts about people, places, or things.
	EntityMemory memory.EntityStore

	// Guardrails validate agent output before it is returned.
	Guardrails []guardrails.Guardrail

	// SelfHealing enables the agent to autonomously correct tool errors.
	SelfHealing bool

	// Cache persists LLM and tool results to save costs and latency.
	Cache llm.Cache

	// UsageMetrics tracks token consumption during the agent's lifecycle.
	UsageMetrics map[string]int

	// AllowDelegation enables this agent to delegate sub-tasks to coworkers.
	AllowDelegation bool

	// StepCallback allows developers to hook into the execution loop for UI streaming.
	StepCallback func(step map[string]interface{})

	// StepReview allows for human-in-the-loop approval before tool execution.
	// Returns true if the action is approved, false otherwise.
	StepReview func(toolName string, toolInput interface{}) bool

	// StepStreamCallback is called for each token generated by the LLM (Streaming).
	StepStreamCallback func(token string)

	// SelfCritique enables internal reflection before returning an answer.
	SelfCritique bool

	// KnowledgeBases provide additional context for the agent's tasks.
	KnowledgeBases []string
	
	// FewShotExamples are used to train the agent's prompt for better accuracy.
	FewShotExamples []string

	// InterruptCh allows sending async instructions/interrupts to the agent mid-execution.
	InterruptCh chan string

	// Sandbox defines the preferred execution environment for the agent's code tools.
	Sandbox string // "local", "docker", "e2b", "wasm"
}

// AgentOption defines a functional option for configuring an Agent.
type AgentOption func(*Agent)

// WithMemory enables memory for the agent with a specific store.
func WithMemory(store memory.Store) AgentOption {
	return func(a *Agent) { 
		a.Memory = store
	}
}

// WithEntityMemory enables entity-specific memory for the agent.
func WithEntityMemory(store memory.EntityStore) AgentOption {
	return func(a *Agent) {
		a.EntityMemory = store
	}
}

// WithTools adds tools to the agent.
func WithTools(t []tools.Tool) AgentOption {
	return func(a *Agent) {
		a.Tools = append(a.Tools, t...)
	}
}

// WithVerbose toggles verbose logging.
func WithVerbose(v bool) AgentOption {
	return func(a *Agent) {
		a.Verbose = v
	}
}

// WithSelfHealing enables or disables autonomous error correction.
func WithSelfHealing(enabled bool) AgentOption {
	return func(a *Agent) { a.SelfHealing = enabled }
}

// WithCache enables result caching for the agent.
func WithCache(cache llm.Cache) AgentOption {
	return func(a *Agent) { a.Cache = cache }
}

// WithMaxIterations sets the maximum number of steps an agent can take.
func WithMaxIterations(max int) AgentOption {
	return func(a *Agent) { a.MaxIterations = max }
}

func NewAgent(role, goal, backstory string, llm llm.Client, opts ...AgentOption) *Agent {
	a := &Agent{
		Role:          role,
		Goal:          goal,
		Backstory:     backstory,
		LLM:           llm,
		MaxIterations: 10, // Default
		UsageMetrics:  make(map[string]int),
	}
	for _, opt := range opts {
		opt(a)
	}
	return a
}

// GetRole returns the agent's role. Implements the delegation.Agent interface.
func (a *Agent) GetRole() string {
	if a.UsageMetrics == nil {
		a.UsageMetrics = make(map[string]int)
	}
	return a.Role
}

// Execute handles running a task, converting from `async def execute_task()`.
// This forms the core logic layer for Agent behavior mapping.
// Provides structured outputs if mapped via Options array.
func (a *Agent) Execute(ctx context.Context, taskInput string, options map[string]interface{}) (interface{}, error) {
	ctx, span := telemetry.StartSpan(ctx, "Agent.Execute")
	if span != nil {
		defer span.End()
		span.SetAttributes(attribute.String("agent.role", a.Role))
	}

	if a.UsageMetrics == nil {
		a.UsageMetrics = make(map[string]int)
	}

	if a.LLM == nil {
		return "Task executed successfully by " + a.Role, nil
	}

	if a.Verbose {
		preview := taskInput
		if len(preview) > 50 {
			preview = preview[:47] + "..."
		}
		defaultLogger.Info("Agent executing", slog.String("role", a.Role), slog.String("task", preview))
	}

	if a.StepCallback != nil {
		a.StepCallback(map[string]interface{}{
			"role":  a.Role,
			"phase": "starting",
			"input": taskInput,
		})
	}

	// Publish telemetry event
	telemetry.GlobalBus.Publish(telemetry.Event{
		Type:      telemetry.EventAgentStarted,
		AgentRole: a.Role,
		Payload: map[string]interface{}{
			"input": taskInput,
		},
	})

	// Memory Recall: inject relevant past context into the prompt
	enrichedInput := taskInput
	if a.Memory != nil {
		enrichedInput = a.recallMemory(ctx, taskInput)
	}

	// Format the ReAct Tooling System Prompt
	toolDescriptions := ""
	for _, t := range a.Tools {
		toolDescriptions += fmt.Sprintf("- %s: %s\n", t.Name(), t.Description())
	}

	// Optional sections for knowledge and few-shot examples
	knowledgeSection := ""
	if len(a.KnowledgeBases) > 0 {
		knowledgeSection = "\n\nKNOWLEDGE BASE CONTEXT:\n" + strings.Join(a.KnowledgeBases, "\n---\n")
	}

	fewShotSection := ""
	if len(a.FewShotExamples) > 0 {
		fewShotSection = "\n\nFEW-SHOT EXAMPLES FOR GUIDANCE:\n" + strings.Join(a.FewShotExamples, "\n---\n")
	}

	systemPrompt := fmt.Sprintf(`You are %s. %s
Your goal is: %s
%s
%s

You have access to the following tools:
%s

To use a tool, you MUST reply with a pure JSON object in this exact format:
{"tool": "ToolName", "input": {"parameter_name": "parameter_value"}}

Once you have gathered all necessary information and are ready to provide the final answer, do NOT return a tool JSON. Simply output your final answer text natively.`, a.Role, a.Backstory, a.Goal, knowledgeSection, fewShotSection, toolDescriptions)

	messages := []llm.Message{
		{Role: "system", Content: systemPrompt},
		{Role: "user", Content: enrichedInput},
	}

	// ---------------------------------------------------------
	// The ReAct Autonomous Tool-Calling Loop Engine
	// ---------------------------------------------------------
	maxLoops := a.MaxIterations
	if maxLoops <= 0 {
		maxLoops = 15 // Default safety guard against infinite loops
	}

	maxRetries := a.MaxRetryLimit
	if maxRetries <= 0 {
		maxRetries = 3
	}

	for i := 0; i < maxLoops; i++ {
		// Check global task cancellation and human interrupts
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case interrupt := <-a.InterruptCh:
			if a.Verbose {
				defaultLogger.Info("🛑 Agent INTERRUPTED", slog.String("agent", a.Role), slog.String("instruction", interrupt))
			}
			messages = append(messages, llm.Message{
				Role:    "user",
				Content: fmt.Sprintf("[USER INTERRUPT]: %s. Please adjust your next action accordingly.", interrupt),
			})
		default:
		}

		if a.StepCallback != nil {
			a.StepCallback(map[string]interface{}{"role": a.Role, "phase": "thinking", "iteration": i + 1})
		}

		// Publish telemetry event
		telemetry.GlobalBus.Publish(telemetry.Event{
			Type:      telemetry.EventAgentThinking,
			AgentRole: strings.Clone(a.Role),
			Payload: map[string]interface{}{
				"iteration": i + 1,
			},
		})

		// If a strict final schema is requested, disable autonomous looping
		if options != nil && options["schema"] != nil {
			mappedSchema := options["schema"]
			response, err := a.LLM.GenerateStructured(ctx, messages, mappedSchema, options)
			return response, err
		}

		// LLM Generation (Streaming vs Block)
		var responseText string
		cacheKey := ""
		if a.Cache != nil {
			cacheKey = llm.GenerateCacheKey(fmt.Sprintf("%T", a.LLM), fmt.Sprintf("%v", messages), options)
			if cached, ok := a.Cache.Get(cacheKey); ok {
				responseText = cached
				if a.Verbose {
					defaultLogger.Info("💾 Agent LLM Cache Hit", slog.String("role", a.Role))
				}
			}
		}

		if responseText == "" {
			if a.StepStreamCallback != nil {
				stream, err := a.LLM.StreamGenerate(ctx, messages, options)
				if err != nil {
					return nil, crewErrors.NewAgentError(strings.Clone(strings.TrimSpace(a.Role)), i+1, fmt.Errorf("%w: %v", crewErrors.ErrLLMFailed, err))
				}
				var sb strings.Builder
				for token := range stream {
					sb.WriteString(token)
					a.StepStreamCallback(token)
				}
				responseText = sb.String()
			} else {
				var err error
				responseText, err = a.LLM.Generate(ctx, messages, options)
				if err != nil {
					return nil, crewErrors.NewAgentError(strings.Clone(strings.TrimSpace(a.Role)), i+1, fmt.Errorf("%w: %v", crewErrors.ErrLLMFailed, err))
				}
			}
			if a.Cache != nil {
				_ = a.Cache.Set(cacheKey, responseText)
			}
		}

		// Elite Tier: Usage Metrics Tracking (Token Heuristic)
		a.UsageMetrics["prompt_tokens"] += len(enrichedInput) / 4
		a.UsageMetrics["completion_tokens"] += len(responseText) / 4

		// ReAct Tool Parsing
		var toolReq struct {
			Tool  string                 `json:"tool"`
			Input map[string]interface{} `json:"input"`
		}

		if err := json.Unmarshal([]byte(strings.TrimSpace(responseText)), &toolReq); err == nil && toolReq.Tool != "" {
			var activeTool tools.Tool
			for _, t := range a.Tools {
				if t.Name() == toolReq.Tool {
					activeTool = t
					break
				}
			}

			if activeTool != nil {
				if a.Verbose {
					defaultLogger.Info("🔨 Agent Tool Triggered", slog.String("agent", a.Role), slog.String("tool", toolReq.Tool), slog.Any("input", toolReq.Input))
				}

				if a.StepCallback != nil {
					a.StepCallback(map[string]interface{}{"role": a.Role, "phase": "tool_execution", "tool": toolReq.Tool})
				}

				// Publish telemetry event
				telemetry.GlobalBus.Publish(telemetry.Event{
					Type:      telemetry.EventToolStarted,
					AgentRole: strings.Clone(a.Role),
					Payload: map[string]interface{}{
						"tool":  toolReq.Tool,
						"input": toolReq.Input,
					},
				})

				// HITL Check
				if activeTool.RequiresReview() && a.StepReview != nil {
					if a.Verbose {
						defaultLogger.Info("⏳ Agent waiting for human approval", slog.String("agent", a.Role), slog.String("tool", toolReq.Tool))
					}
					if !a.StepReview(toolReq.Tool, toolReq.Input) {
						observation := "Tool Execution Denied by human."
						messages = append(messages, llm.Message{Role: "assistant", Content: responseText})
						messages = append(messages, llm.Message{Role: "user", Content: observation})
						continue
					}
				}

				// Tool Execution
				var toolResult string
				var toolErr error
				toolCacheKey := ""
				if a.Cache != nil {
					toolCacheKey = fmt.Sprintf("tool:%s|input:%v", toolReq.Tool, toolReq.Input)
					if cached, ok := a.Cache.Get(toolCacheKey); ok {
						toolResult = cached
						if a.Verbose {
							defaultLogger.Info("💾 Agent Tool Cache Hit", slog.String("role", a.Role), slog.String("tool", toolReq.Tool))
						}
					}
				}

				if toolResult == "" {
					toolResult, toolErr = activeTool.Execute(ctx, toolReq.Input)
					if toolErr == nil && a.Cache != nil {
						_ = a.Cache.Set(toolCacheKey, toolResult)
					}
				}

				// Publish telemetry event
				telemetry.GlobalBus.Publish(telemetry.Event{
					Type:      telemetry.EventToolFinished,
					AgentRole: strings.Clone(a.Role),
					Payload: map[string]interface{}{
						"tool":   toolReq.Tool,
						"result": toolResult,
						"error":  toolErr,
					},
				})

				var observation string
				if toolErr != nil {
					if a.SelfHealing && maxRetries > 0 {
						maxRetries--
						observation = fmt.Sprintf("Tool Error: %v. Please correct your parameters and try again.", toolErr)
						defaultLogger.Warn("Self-healing triggered", slog.String("agent", a.Role), slog.String("error", toolErr.Error()))
					} else {
						observation = fmt.Sprintf("Fatal Tool Error: %v", toolErr)
						defaultLogger.Error("❌ Tool Execution Failed", slog.String("agent", a.Role), slog.String("tool", toolReq.Tool), slog.Any("error", toolErr))
					}
				} else {
					observation = fmt.Sprintf("Observation: %v", toolResult)
					if a.Verbose {
						defaultLogger.Info("✅ Tool Execution Success", slog.String("agent", a.Role), slog.String("tool", toolReq.Tool))
					}
				}

				messages = append(messages, llm.Message{Role: "assistant", Content: responseText})
				messages = append(messages, llm.Message{Role: "user", Content: observation})
				continue
			} else {
				// The LLM hallucinated a tool name that doesn't exist
				messages = append(messages, llm.Message{Role: "assistant", Content: responseText})
				messages = append(messages, llm.Message{Role: "user", Content: fmt.Sprintf(
					"Observation Error: The tool '%s' does not exist. Available tools are: \n%s",
					toolReq.Tool, toolDescriptions)})
				continue
			}
		}

		// Final Result Handling
		if len(a.Guardrails) > 0 {
			if err := guardrails.RunAll(a.Guardrails, responseText); err != nil {
				if maxRetries > 0 {
					maxRetries--
					messages = append(messages, llm.Message{Role: "assistant", Content: responseText})
					messages = append(messages, llm.Message{Role: "user", Content: fmt.Sprintf("Validation Error: %v. Please regenerate.", err)})
					if a.Verbose {
						defaultLogger.Warn("⚠️ Guardrail failed, retrying", slog.String("agent", a.Role), slog.String("error", err.Error()))
					}
					continue
				}
				return nil, crewErrors.NewAgentError(strings.Clone(strings.TrimSpace(a.Role)), i+1,
					fmt.Errorf("%w: %v", crewErrors.ErrGuardrailFailed, err))
			}
		}

		if a.Verbose {
			defaultLogger.Info("✅ Agent loop finalized", slog.String("agent", a.Role))
		}

		if a.Memory != nil {
			a.saveMemory(ctx, taskInput, responseText)
		}

		// Self-Critique / Internal Reflection
		if a.SelfCritique {
			critiquePrompt := fmt.Sprintf("Critique your own response for accuracy and tone. If it is perfect, respond 'APPROVED'. Otherwise, suggest improvements.\nYour Response: %s", responseText)
			critique, err := a.LLM.Generate(ctx, []llm.Message{
				{Role: "system", Content: "You are a critical self-reviewer."},
				{Role: "user", Content: critiquePrompt},
			}, nil)
			
			if err == nil && !strings.Contains(strings.ToUpper(critique), "APPROVED") {
				if a.Verbose {
					defaultLogger.Info("🔄 Agent self-correcting based on internal critique", slog.String("role", a.Role))
				}
				// Re-run with critique
				return a.Execute(ctx, taskInput+"\n\nINTERNAL CRITIQUE: "+critique, options)
			}
		}

		// Publish telemetry event
		telemetry.GlobalBus.Publish(telemetry.Event{
			Type:      telemetry.EventAgentFinished,
			AgentRole: strings.Clone(a.Role),
			Payload: map[string]interface{}{
				"result": responseText,
			},
		})

		return responseText, nil
	}

	return nil, crewErrors.NewAgentError(strings.Clone(strings.TrimSpace(a.Role)), maxLoops,
		fmt.Errorf("%w (%d iterations)", crewErrors.ErrMaxIterations, maxLoops))
}

// recallMemory queries the agent's memory store for relevant past context
// and prepends it to the task input.
func (a *Agent) recallMemory(ctx context.Context, taskInput string) string {
	if a.LLM == nil {
		return taskInput
	}

	var sb strings.Builder
	hasContext := false

	// 1. Vector Search (Short-Term/Long-Term)
	if a.Memory != nil {
		vector, err := a.LLM.GenerateEmbedding(ctx, taskInput)
		if err == nil {
			items, _ := a.Memory.Search(ctx, vector, 2)
			if len(items) > 0 {
				if !hasContext {
					sb.WriteString("RELEVANT PAST CONTEXT:\n")
					hasContext = true
				}
				for i, item := range items {
					sb.WriteString(fmt.Sprintf("--- Historical Memory %d ---\n%s\n", i+1, item.Text))
				}
			}
		}
	}

	// 2. Entity Fact Retrieval
	if a.EntityMemory != nil {
		// Use the task input as a keyword search for entities
		entities, _ := a.EntityMemory.Search(ctx, taskInput, 2)
		if len(entities) > 0 {
			if !hasContext {
				sb.WriteString("RELEVANT PAST CONTEXT:\n")
				hasContext = true
			}
			for i, entity := range entities {
				sb.WriteString(fmt.Sprintf("--- Tracked Entity %d ---\n%s\n", i+1, entity.Text))
			}
		}
	}

	if hasContext {
		sb.WriteString("--------------------------\n\n")
		sb.WriteString(taskInput)
		return sb.String()
	}

	return taskInput
}

// saveMemory persists the task input and result to the agent's memory store.
func (a *Agent) saveMemory(ctx context.Context, taskInput, result string) {
	content := fmt.Sprintf("Task: %s\nResult: %s", taskInput, result)

	// Generate embedding for storage
	vector, err := a.LLM.GenerateEmbedding(ctx, content)
	if err != nil {
		if a.Verbose {
			defaultLogger.Warn("Memory save: embedding generation failed", slog.String("error", err.Error()))
		}
		return
	}

	item := &memory.MemoryItem{
		ID:     fmt.Sprintf("agent_%s_%d", a.Role, len(content)),
		Text:   content,
		Vector: vector,
		Metadata: map[string]interface{}{
			"agent_role": a.Role,
			"type":       "execution_result",
		},
	}
	_ = a.Memory.Add(ctx, item)

	// If EntityMemory is present, we try to extract and save specific facts
	if a.EntityMemory != nil {
		go a.extractAndStoreEntities(ctx, result)
	}
}

// extractAndStoreEntities uses the LLM to find entities/facts in a result and saves them.
func (a *Agent) extractAndStoreEntities(ctx context.Context, text string) {
	prompt := fmt.Sprintf(
		"Extract key entities and facts from the following text. "+
		"Return ONLY a JSON array of objects like: [{\"entity\": \"Name\", \"value\": \"Value\", \"description\": \"Context\"}]. "+
		"If none found, return [].\nText: %s", text)

	response, err := a.LLM.Generate(ctx, []llm.Message{
		{Role: "system", Content: "You are a precise data extractor."},
		{Role: "user", Content: prompt},
	}, nil)

	if err != nil {
		return
	}

	var entities []struct {
		Entity      string `json:"entity"`
		Value       string `json:"value"`
		Description string `json:"description"`
	}

	if err := json.Unmarshal([]byte(strings.TrimSpace(response)), &entities); err == nil {
		for _, e := range entities {
			_ = a.EntityMemory.Upsert(ctx, e.Entity, e.Value, e.Description)
		}
	}
}

