// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: api/proto/agent_mesh.proto

package mesh

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskDescription string                 `protobuf:"bytes,1,opt,name=task_description,json=taskDescription,proto3" json:"task_description,omitempty"`
	AgentRole       string                 `protobuf:"bytes,2,opt,name=agent_role,json=agentRole,proto3" json:"agent_role,omitempty"`
	AgentGoal       string                 `protobuf:"bytes,3,opt,name=agent_goal,json=agentGoal,proto3" json:"agent_goal,omitempty"`
	ContextJson     string                 `protobuf:"bytes,4,opt,name=context_json,json=contextJson,proto3" json:"context_json,omitempty"`
	SessionId       string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_api_proto_agent_mesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_mesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_mesh_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetTaskDescription() string {
	if x != nil {
		return x.TaskDescription
	}
	return ""
}

func (x *TaskRequest) GetAgentRole() string {
	if x != nil {
		return x.AgentRole
	}
	return ""
}

func (x *TaskRequest) GetAgentGoal() string {
	if x != nil {
		return x.AgentGoal
	}
	return ""
}

func (x *TaskRequest) GetContextJson() string {
	if x != nil {
		return x.ContextJson
	}
	return ""
}

func (x *TaskRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	AgentRole     string                 `protobuf:"bytes,2,opt,name=agent_role,json=agentRole,proto3" json:"agent_role,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_api_proto_agent_mesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_mesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_mesh_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TaskResponse) GetAgentRole() string {
	if x != nil {
		return x.AgentRole
	}
	return ""
}

func (x *TaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_proto_agent_mesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_mesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_mesh_proto_rawDescGZIP(), []int{2}
}

func (x *StatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentRole     string                 `protobuf:"bytes,1,opt,name=agent_role,json=agentRole,proto3" json:"agent_role,omitempty"`
	UpdateType    string                 `protobuf:"bytes,2,opt,name=update_type,json=updateType,proto3" json:"update_type,omitempty"` // "thinking", "tool_use", "finished"
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusUpdate) Reset() {
	*x = StatusUpdate{}
	mi := &file_api_proto_agent_mesh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdate) ProtoMessage() {}

func (x *StatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_mesh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdate.ProtoReflect.Descriptor instead.
func (*StatusUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_mesh_proto_rawDescGZIP(), []int{3}
}

func (x *StatusUpdate) GetAgentRole() string {
	if x != nil {
		return x.AgentRole
	}
	return ""
}

func (x *StatusUpdate) GetUpdateType() string {
	if x != nil {
		return x.UpdateType
	}
	return ""
}

func (x *StatusUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	K             int32                  `protobuf:"varint,2,opt,name=k,proto3" json:"k,omitempty"`
	Collection    string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	Filters       map[string]string      `protobuf:"bytes,4,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_api_proto_agent_mesh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_mesh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_mesh_proto_rawDescGZIP(), []int{4}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *SearchRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *SearchRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snippets      []*KnowledgeSnippet    `protobuf:"bytes,1,rep,name=snippets,proto3" json:"snippets,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_api_proto_agent_mesh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_mesh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_mesh_proto_rawDescGZIP(), []int{5}
}

func (x *SearchResponse) GetSnippets() []*KnowledgeSnippet {
	if x != nil {
		return x.Snippets
	}
	return nil
}

func (x *SearchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SearchResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type KnowledgeSnippet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeSnippet) Reset() {
	*x = KnowledgeSnippet{}
	mi := &file_api_proto_agent_mesh_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeSnippet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeSnippet) ProtoMessage() {}

func (x *KnowledgeSnippet) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_mesh_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeSnippet.ProtoReflect.Descriptor instead.
func (*KnowledgeSnippet) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_mesh_proto_rawDescGZIP(), []int{6}
}

func (x *KnowledgeSnippet) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *KnowledgeSnippet) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *KnowledgeSnippet) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *KnowledgeSnippet) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type IndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Collection    string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexRequest) Reset() {
	*x = IndexRequest{}
	mi := &file_api_proto_agent_mesh_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexRequest) ProtoMessage() {}

func (x *IndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_mesh_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexRequest.ProtoReflect.Descriptor instead.
func (*IndexRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_mesh_proto_rawDescGZIP(), []int{7}
}

func (x *IndexRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *IndexRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *IndexRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *IndexRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type IndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexResponse) Reset() {
	*x = IndexResponse{}
	mi := &file_api_proto_agent_mesh_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexResponse) ProtoMessage() {}

func (x *IndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_mesh_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexResponse.ProtoReflect.Descriptor instead.
func (*IndexResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_mesh_proto_rawDescGZIP(), []int{8}
}

func (x *IndexResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IndexResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *IndexResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_api_proto_agent_mesh_proto protoreflect.FileDescriptor

const file_api_proto_agent_mesh_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/agent_mesh.proto\x12\x04mesh\"\xb8\x01\n" +
	"\vTaskRequest\x12)\n" +
	"\x10task_description\x18\x01 \x01(\tR\x0ftaskDescription\x12\x1d\n" +
	"\n" +
	"agent_role\x18\x02 \x01(\tR\tagentRole\x12\x1d\n" +
	"\n" +
	"agent_goal\x18\x03 \x01(\tR\tagentGoal\x12!\n" +
	"\fcontext_json\x18\x04 \x01(\tR\vcontextJson\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\"\x84\x01\n" +
	"\fTaskResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x1d\n" +
	"\n" +
	"agent_role\x18\x02 \x01(\tR\tagentRole\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\".\n" +
	"\rStatusRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"h\n" +
	"\fStatusUpdate\x12\x1d\n" +
	"\n" +
	"agent_role\x18\x01 \x01(\tR\tagentRole\x12\x1f\n" +
	"\vupdate_type\x18\x02 \x01(\tR\n" +
	"updateType\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xcb\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\f\n" +
	"\x01k\x18\x02 \x01(\x05R\x01k\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12:\n" +
	"\afilters\x18\x04 \x03(\v2 .mesh.SearchRequest.FiltersEntryR\afilters\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x01\n" +
	"\x0eSearchResponse\x122\n" +
	"\bsnippets\x18\x01 \x03(\v2\x16.mesh.KnowledgeSnippetR\bsnippets\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xd9\x01\n" +
	"\x10KnowledgeSnippet\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\x12@\n" +
	"\bmetadata\x18\x04 \x03(\v2$.mesh.KnowledgeSnippet.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdb\x01\n" +
	"\fIndexRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12<\n" +
	"\bmetadata\x18\x04 \x03(\v2 .mesh.IndexRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	"\rIndexResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage2\xf8\x01\n" +
	"\vMeshService\x125\n" +
	"\fDelegateTask\x12\x11.mesh.TaskRequest\x1a\x12.mesh.TaskResponse\x129\n" +
	"\fStreamStatus\x12\x13.mesh.StatusRequest\x1a\x12.mesh.StatusUpdate0\x01\x12<\n" +
	"\x0fSearchKnowledge\x12\x13.mesh.SearchRequest\x1a\x14.mesh.SearchResponse\x129\n" +
	"\x0eIndexKnowledge\x12\x12.mesh.IndexRequest\x1a\x13.mesh.IndexResponseB\x0eZ\fpkg/api/meshb\x06proto3"

var (
	file_api_proto_agent_mesh_proto_rawDescOnce sync.Once
	file_api_proto_agent_mesh_proto_rawDescData []byte
)

func file_api_proto_agent_mesh_proto_rawDescGZIP() []byte {
	file_api_proto_agent_mesh_proto_rawDescOnce.Do(func() {
		file_api_proto_agent_mesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_agent_mesh_proto_rawDesc), len(file_api_proto_agent_mesh_proto_rawDesc)))
	})
	return file_api_proto_agent_mesh_proto_rawDescData
}

var file_api_proto_agent_mesh_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_agent_mesh_proto_goTypes = []any{
	(*TaskRequest)(nil),      // 0: mesh.TaskRequest
	(*TaskResponse)(nil),     // 1: mesh.TaskResponse
	(*StatusRequest)(nil),    // 2: mesh.StatusRequest
	(*StatusUpdate)(nil),     // 3: mesh.StatusUpdate
	(*SearchRequest)(nil),    // 4: mesh.SearchRequest
	(*SearchResponse)(nil),   // 5: mesh.SearchResponse
	(*KnowledgeSnippet)(nil), // 6: mesh.KnowledgeSnippet
	(*IndexRequest)(nil),     // 7: mesh.IndexRequest
	(*IndexResponse)(nil),    // 8: mesh.IndexResponse
	nil,                      // 9: mesh.SearchRequest.FiltersEntry
	nil,                      // 10: mesh.KnowledgeSnippet.MetadataEntry
	nil,                      // 11: mesh.IndexRequest.MetadataEntry
}
var file_api_proto_agent_mesh_proto_depIdxs = []int32{
	9,  // 0: mesh.SearchRequest.filters:type_name -> mesh.SearchRequest.FiltersEntry
	6,  // 1: mesh.SearchResponse.snippets:type_name -> mesh.KnowledgeSnippet
	10, // 2: mesh.KnowledgeSnippet.metadata:type_name -> mesh.KnowledgeSnippet.MetadataEntry
	11, // 3: mesh.IndexRequest.metadata:type_name -> mesh.IndexRequest.MetadataEntry
	0,  // 4: mesh.MeshService.DelegateTask:input_type -> mesh.TaskRequest
	2,  // 5: mesh.MeshService.StreamStatus:input_type -> mesh.StatusRequest
	4,  // 6: mesh.MeshService.SearchKnowledge:input_type -> mesh.SearchRequest
	7,  // 7: mesh.MeshService.IndexKnowledge:input_type -> mesh.IndexRequest
	1,  // 8: mesh.MeshService.DelegateTask:output_type -> mesh.TaskResponse
	3,  // 9: mesh.MeshService.StreamStatus:output_type -> mesh.StatusUpdate
	5,  // 10: mesh.MeshService.SearchKnowledge:output_type -> mesh.SearchResponse
	8,  // 11: mesh.MeshService.IndexKnowledge:output_type -> mesh.IndexResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_agent_mesh_proto_init() }
func file_api_proto_agent_mesh_proto_init() {
	if File_api_proto_agent_mesh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_agent_mesh_proto_rawDesc), len(file_api_proto_agent_mesh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_agent_mesh_proto_goTypes,
		DependencyIndexes: file_api_proto_agent_mesh_proto_depIdxs,
		MessageInfos:      file_api_proto_agent_mesh_proto_msgTypes,
	}.Build()
	File_api_proto_agent_mesh_proto = out.File
	file_api_proto_agent_mesh_proto_goTypes = nil
	file_api_proto_agent_mesh_proto_depIdxs = nil
}
